# Column Mapping Strategy
column_matching : 
fuzzy_words: "can_be_handled"
confidence_score : 0.98
rules:
   target: transaction_id
   candidate:
    -VoucherID
    -Transaction_id
    -InvoiceNo
   priority: high


   target: amount
   candidate:
   -debit_amount
   -credit_amount
   -amount
   priority: high


   
   target: date
   candidate:
   -transactionDate
   -Date
   -Issuedate
   priority: medium

target: party_name
   candidate:
   -PartyName
   -clientName
   -vendorName
  